XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates
SRK_TEMPLATES_DIR=SRK\ Templates

install_templates:
	rm -R -f $(XCODE_USER_TEMPLATES_DIR)/$(SRK_TEMPLATES_DIR)
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	cp -R -f $(SRK_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

uninstall_templates:
	rm -R $(XCODE_USER_TEMPLATES_DIR)/$(SRK_TEMPLATES_DIR)
