//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ SRK. All rights reserved.
//
//  This file was generated by the Shreyansh Raj Keshri 👾
//


import Foundation

public class JSONParser {
    private let jsonDecoder = JSONDecoder()
    
    func decode<T: Codable>(_ data: Data) -> T? {
        return try? jsonDecoder.decode(T.self, from: data)
    }
}
